config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  get 'blogs/show'
  get 'blogs/new'
  get 'blogs/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resourcesの書き方は、コロン(:)をつける位置によってエラーがよく発生してしまいます
  # resources :posts, only: [:index]という書き方もある、resources :posts, :indexは誤り
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
# indexからeditまでがview関連
# @のインスタンス変数はviewに渡す用
  def index
  # 記事を全件取得
  # @blogsはアクションから渡ってきている投稿記事のデータ
  # @blog(s)はHTTPメソッドで使用するリソースの設定をしている
      @blogs = Blog.all
  end

  def show
  	# URLにパラメータが設定されているので、params[:id]と記述することで記事のIDを取得
  	  @blog = Blog.find(params[:id])
  end

  def new
  	# @インスタンス変数 = モデル名(大文字単数).new
  	  @blog = Blog.new
  end

  def edit
  	  @blog = Blog.find(params[:id])
  end

# 以下view関連なし
  def create
  	  # ローカルのインスタンス変数=モデル名.new(アクション名)
  	  blog = Blog.new(blog_params)
  	  blog.save
  	  redirect_to blogs_path # トップページに飛ぶ
  end

  def update # 6
  	  blog = Blog.find(params[:id])
  	  blog.update(blog_params)
  	  redirect_to blogs_path(blog) # トップページに飛ぶ
  end

  def destroy # 7
  	  blog = Blog.find(params[:id])
  	  blog.destroy
  	  redirect_to blogs_path # トップページに飛ぶ
  end

# Strong Parametersの設定
  private
  # blog_paramsというアクション
  def blog_params
  	params.require(:blog).permit(:title, :category, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<h1>編集画面</h1>
<!-- form_for部分 -->
<%= form_for(@blog) do |f| %> <!-- 最後にエンド -->
	<h4>タイトル</h4>
	<%= f.text_field :title %>

	<h4>カテゴリー</h4>
	<%= f.text_field :category %>

	<h4>本文</h4>
	<%= f.text_area :body %> <!-- .erb -->

	<%= f.submit '保存' %> <!-- .erb submit=提示する -->

<% end %>  <!-- .erb -->

app/views/blogs/index.html.erb
<header>
    <h1 class="headline">
      <a href="#">CARAVAN</a>
    </h1>
    <div class="social">
      <i class="fa fa-facebook-square"></i>
      <i class="fa fa-twitter-square"></i>
      <i class="fa fa-instagram"></i>
    </div>
  </header>
 
  <nav>
    <ul class="nav-list">
      <li class="nav-list-item">
        <a href="#">Home</a>
      </li>
      <li class="nav-list-item">About</li>
      <li class="nav-list-item">Topic</li>
    </ul>
  </nav>
 
  <div class="main-visual">
    <div class="main-visual-content">
      <p class="main-visual-text">
        The world is a book<br>
        and those who do not travel<br>
        read only one page.
      </p>
      <p class="main-visual-name">
        St. Augustine
      </p>
    </div>
  </div>
 
  <main class="clearfix">
    <section class="blog">
      <h2 class="blog-headline">Recent Blogs</h2>
      <div class="blog-box">
        <!-- .eachでループ処理する -->
        <% @blogs.each do |blog| %> <!-- =が付かない(サイトに表示させない) -->
        <div class="blog-item clearfix">
          <!-- blog-imageをdiv -->
          <div class="blog-image"><%= image_tag('img/forest.jpg',  class: 'blog-image') %></div>
          <section class="blog-text">
            <!-- blog-text-headlineにlink_toで詳細ページへ飛ぶ設定 -->
            <h3 class="blog-text-headline"><%= link_to blog.title, blog_path(blog) %></h3>
            <!-- June 19, 2017を自動的にデータを作成した日時を記録へ変更 -->
            <p class="blog-date"><%= blog.created_at %></p>
            <!-- 手打ちNatureをcategory(選択肢)から選択へ変更 -->
            <span class="category"><%= blog.category %></span>
          </section>
        </div>
        <% end %>  <!-- .erb -->
      <!-- ループ処理をしたので他の記事削除 -->
      </div>
      <div class="pagination">
        <p><<</p>
        <p><</p>
        <p>1</p>
        <p>2</p>
        <p>3</p>
        <p>></p>
        <p>>></p>
      </div>
    </section>
    <div class="sidebar">
      <section class="popular">
        <h2 class="sidebar-headline">Popular</h2>
        <div class="sidebar-contents">
          <p class="popular-text">To solve old problems,<br>study new species</p>
          <p class="popular-text">Why Earth may someday<br>look like Mars</p>
          <p class="popular-text">What will humans look<br>like in 100 years?</p>
          <p class="popular-text">How to grow a forest<br>in your backyard</p>
          <p class="popular-text">How humans could evolve<br>to survive in space</p>
        </div>
      </section>
      <section class="instagram">
        <h2 class="instagram-headline">Instagram</h2>
        <div class="sidebar-contents clearfix">
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
          <div class="instagram-box"></div>
        </div>
      </section>
      <section class="categories">
        <h2 class="categories-headline">Categories</h2>
        <div class="sidebar-contents">
          <p class="categories-text">Technology(15)</p>
          <p class="categories-text">Business(23)</p>
          <p class="categories-text">Entertainment(12)</p>
          <p class="categories-text">Nature(32)</p>
          <p class="categories-text">Education(9)</p>
          <p class="categories-text">Adventure(23)</p>
          <p class="categories-text">Communication(14)</p>
        </div>
      </section>
    </div>
  </main>
 
  <footer>
    <p class="footer-text">© All rights recerved by Infratop.Inc.</p>
  </footer>

app/views/blogs/new.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@blog) do |f| %> <!-- 最後にエンド -->

	<h4>タイトル</h4>
	<%= f.text_field :title %>

	<h4>カテゴリー</h4>
	<%= f.text_field :category %>

	<h4>本文</h4>
	<%= f.text_area :body %> <!-- .erb -->

	<%= f.submit '投稿' %> <!-- .erb submit=提示する -->

<% end %>  <!-- .erb -->

app/views/blogs/show.html.erb
<header>
  <h1 class="headline">
  	<!-- CARAVANにlink_toで全記事一覧へ飛ぶ設定 -->
    <%= link_to "CARAVAN", blogs_path %>
  </h1>
  <div class="social">
    <i class="fa fa-facebook-square"></i>
    <i class="fa fa-twitter-square"></i>
    <i class="fa fa-instagram"></i>
  </div>
</header>
 
<nav>
  <ul class="nav-list">
    <li class="nav-list-item">
      <!-- <a href="#">ページトップへ移動</a> -->
      <a href="#">Home</a>
    </li>
    <li class="nav-list-item">About</li>
    <li class="nav-list-item">Topic</li>
  </ul>
</nav>
 
<div class="main-visual">
  <div class="main-visual-content">
    <p class="main-visual-text">
      The world is a book<br>
      and those who do not travel<br>
      read only one page.
    </p>
    <p class="main-visual-name">
      St. Augustine
    </p>
  </div>
</div>
 
<main class="clearfix">
  <section class="single-blog">
	  <h2 class="blog-headline">Blog</h2>
	  <section class="blog-box">
	    <h3 class="blog-box-headline">
	    	<!-- params[:id]でtitleのidを参照する -->
	      <%= @blog.title %>
	    </h3>
	    <div class="blog-box-content">
	      <p class="category">
	      	<!-- params[:id]でcategoryのidを参照する -->
	        <%= @blog.category %>
	      </p>
	      <p class="blog-date">
	      	<!-- params[:id]でcreated_atのidを参照する -->
	        <%= @blog.created_at %>
	      </p>
	    </div>
	    <!-- HTMLの<img>タグを生成するためのメソッド class:(要素を分類するクラス名)はコマンド記法らしい -->
	    <%= image_tag "img/forest.jpg", class:"single-image" %>
	    <p class="single-text">
	      <%= @blog.body %>
	    </p>
		<!-- <a href="#">をeditアクションからリソース(投稿記事)を取得するように設定 -->
	    <%= link_to "編集", edit_blog_path(@blog) %>
	    <!-- <a href="#">を取得したリソース(投稿記事)を削除するように設定 -->
	    <%= link_to "削除", blog_path(@blog), method: :delete %>
	    <div class="author-case clearfix"><!-- author=著者,case=(人の)状態 -->
	      <div class="author-image"></div>
	      <div class="author-box">
	        <p class="author-name">By JOHN SMITH / Photographer</p>
	        <p class="author-text">His black and white landscapes, often captured at times<br>
	        of the day and night when the light is fleeting, or in poor<br>
	        weather conditions, such as rain, fog, or snow, are<br>reminiscent of the calm in a storm all with an ethereal<br>quality. </p>
	      </div>
	    </div>
	  </section>
	</section>
 
  <div class="sidebar">
    <section class="popular">
      <h2 class="sidebar-headline">Popular</h2>
      <div class="sidebar-contents">
        <p class="popular-text">To solve old problems,<br>study new species</p>
        <p class="popular-text">Why Earth may someday<br>look like Mars</p>
        <p class="popular-text">What will humans look<br>like in 100 years?</p>
        <p class="popular-text">How to grow a forest<br>in your backyard</p>
        <p class="popular-text">How humans could evolve<br>to survive in space</p>
      </div>
    </section>
    <section class="instagram">
      <h2 class="instagram-headline">Instagram</h2>
      <div class="sidebar-contents clearfix">
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
      </div>
    </section>
    <section class="categories">
      <h2 class="categories-headline">Categories</h2>
      <div class="sidebar-contents">
        <p class="categories-text">Technology(15)</p>
        <p class="categories-text">Business(23)</p>
        <p class="categories-text">Entertainment(12)</p>
        <p class="categories-text">Nature(32)</p>
        <p class="categories-text">Education(9)</p>
        <p class="categories-text">Adventure(23)</p>
        <p class="categories-text">Communication(14)</p>
      </div>
    </section>
  </div>
</main>
<footer>
<p class="footer-text">© All rights recerved by Infratop.Inc.</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CARAVAN</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
    <%= yield %>
  </body>
</html>